name: Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Run command `uv run python main.py`
        2. Send MCP request '...'
        3. See error
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - MCP Server Core
        - Base Tools (add_text, add_files, cognify, search)
        - Dataset Tools
        - Graph Tools  
        - Temporal Tools
        - Ontology Tools
        - Memory Tools
        - Self-improving Tools
        - Diagnostic Tools
        - Configuration/Settings
        - Authentication
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of cognee-mcp-v2 are you running?
      placeholder: v2.0.0
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      options:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - Other
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: |
        Please provide environment details:
        - uv version: `uv --version`
        - Virtual environment: Active/Inactive
        - Relevant environment variables (redact sensitive values)
      placeholder: |
        uv version: 0.1.0
        Virtual environment: Active
        LOG_LEVEL=DEBUG
        FEATURE_TIME_AWARENESS=true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
